# Generated by Django 2.2.4 on 2019-08-06 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_leads_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='entityid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Leads'),
        ),
    ]
