# Generated by Django 2.2.4 on 2019-08-07 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20190806_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='entityid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='client.Leads'),
        ),
    ]
