# Generated by Django 2.2.4 on 2019-08-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='cname',
        ),
    ]
