# Generated by Django 2.2.4 on 2019-08-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20190801_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
